// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login_Invalid', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login_Invalid', async function() {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("seng401@gmail.com")
    {
      const element = await driver.findElement(By.css(".MuiButton-contained"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    assert(await driver.switchTo().alert().getText() == "Incorrect Username or Password")
  })
})
