// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Make_Post', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Make_Post', async function() {
    await driver.get("http://localhost:3000/dashboard/discussion")
    await driver.manage().window().setRect({ width: 1536, height: 824 })
    await driver.findElement(By.css(".post-editor-subject")).click()
    await driver.findElement(By.css(".post-editor-subject")).sendKeys("Test 1")
    await driver.findElement(By.css(".post-editor-body")).click()
    await driver.findElement(By.css(".post-editor-body")).sendKeys("Heellllooooo")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(4) .panel-body"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
