// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register_Existing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register_Existing', async function() {
    await driver.get("http://localhost:3000/register")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("michie")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("1234")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    assert(await driver.switchTo().alert().getText() == "Email already in use. (Did you mean to login??)")
  })
})
