// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register_New', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register_New', async function() {
    await driver.get("http://localhost:3000/register")
    await driver.manage().window().setRect({ width: 788, height: 824 })
    await driver.findElement(By.id("username")).sendKeys("seng401")
    await driver.findElement(By.css("#root > div")).click()
    await driver.findElement(By.id("password")).sendKeys("happy")
    await driver.findElement(By.css(".MuiButton-contained")).click()
  })
})
