// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Reply_Discussion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Reply_Discussion', async function() {
    await driver.get("http://localhost:3000/dashboard/discussion")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.findElement(By.css("a:nth-child(2) .panel-body")).click()
    await driver.findElement(By.css(".form-control")).click()
    await driver.findElement(By.css(".form-control")).sendKeys("Hey! How\'s it going??")
    await driver.findElement(By.css(".btn")).click()
  })
})
